---
- hosts: otw
  remote_user: opendoors_web
  sudo: yes

  vars_prompt:
    - name: "site_keyname"
      prompt: "Key name for new site (no spaces, no punctuation) ? "
      private: no
    - name: "site_port"
      prompt: "Port number for new site (> 9000) ? "
      private: no

  tasks:

  - name: Delete application folder
    local_action: shell rm -rf {{website_path}}/{{site_keyname}}
    become_user: {{ local_user }}

  - name: Create application folder
    local_action: shell cp -r {{code_path}} {{website_path}}/{{site_keyname}}
    become_user: {{ local_user }}

  - name: Rename new application
    template:
      src: server.conf
      dest: "{{website_path}}/{{ site_keyname }}/conf/server.conf"
    become_user: {{ local_user }}
    delegate_to: 127.0.0.1

  - name: Generate distribution for Play application
    local_action: shell sbt clean dist
    become_user: {{ local_user }}
    args:
      chdir: "{{ website_path }}/{{ site_keyname }}"

  - name: Kill the Play application on the remote site (if applicable)
    shell: "kill -9 $(cat /var/www/{{ site_keyname }}/RUNNING_PID)"
    ignore_errors: yes

  - name: Delete directory for new site
    file: path=/var/www/{{ site_keyname }} state=absent

  - name: Create directory for new site
    file: path=/var/www/{{ site_keyname }} state=directory owner=opendoors_web group=otwmysql mode=a+w

  - name: Generate init.d script for site
    template:
      src: dist-play-app-initd
      dest: /etc/init.d/dist-play-{{ site_keyname }}-initd
      mode: a+x
      owner: opendoors_web
      group: otwmysql

  - name: Copy site files to remote server
    unarchive:
      copy: yes
      src: "{{ website_path }}/{{ site_keyname }}/target/universal/{{ site_keyname }}.zip"
      dest: /var/www/
      owner: opendoors_web
      group: otwmysql
      mode: g+rwx

  - name: Update Nginx config with site details
    blockinfile:
      dest: /etc/nginx/sites-available/opendoors-web.ao3.org
      marker: "# ------ {mark} {{ site_keyname }} on {{ site_port }}"
      insertbefore: "^\\s+location / {"
      content: |

            location /{{ site_keyname }} {
              proxy_pass http://127.0.0.1:{{ site_port }}/{{ site_keyname }};
            }


  - name: Create MySql database
    mysql_db:
      name: {{ site_keyname }}
      login_user: {{ mysql_user }}
      login_password: {{ mysql_password }}
      state: present

  - name: Start the Play application on the remote site
    command: "/etc/init.d/dist-play-{{ site_keyname }}-initd start"
    async: 15
    poll: 5
    ignore_errors: yes

  - name: Restart nginx
    action: service name=nginx state=restarted
