---
- hosts: otw
  remote_user: opendoors_web
  sudo: yes

  roles:
    - williamyeh.oracle-java

  vars:
    java_version: 8
    java_subversion: 66

  tasks:

  - name: Install packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - nginx
      - mysql
      - python-mysqldb
